//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ultz.Oppy.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ultz.Oppy.Properties.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server received an invalid response from an upstream server..
        /// </summary>
        internal static string BadGateway {
            get {
                return ResourceManager.GetString("BadGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming request was malformed..
        /// </summary>
        internal static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request could not be processed due to a conflict in resource state..
        /// </summary>
        internal static string Conflict {
            get {
                return ResourceManager.GetString("Conflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server doesn&apos;t meet the request&apos;s expectations..
        /// </summary>
        internal static string ExpectationFailed {
            get {
                return ResourceManager.GetString("ExpectationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request failed because it depended on another failed request..
        /// </summary>
        internal static string FailedDependency {
            get {
                return ResourceManager.GetString("FailedDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming request was forbidden from accessing the resource..
        /// </summary>
        internal static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server didn&apos;t receive a timely response from an upstream server..
        /// </summary>
        internal static string GatewayTimeout {
            get {
                return ResourceManager.GetString("GatewayTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Te resource is unavailable and will remain unavailable indefinitely..
        /// </summary>
        internal static string Gone {
            get {
                return ResourceManager.GetString("Gone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error: The handler ran dry with no error and a partial response..
        /// </summary>
        internal static string HandlerRanDry {
            get {
                return ResourceManager.GetString("HandlerRanDry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server does not support the HTTP protocol version used..
        /// </summary>
        internal static string HttpVersionNotSupported {
            get {
                return ResourceManager.GetString("HttpVersionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unable to store the representation needed to complete the request..
        /// </summary>
        internal static string InsufficientStorage {
            get {
                return ResourceManager.GetString("InsufficientStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An internal server error has occurred..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request did not specify the length of its content..
        /// </summary>
        internal static string LengthRequired {
            get {
                return ResourceManager.GetString("LengthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource the request is trying to access is locked..
        /// </summary>
        internal static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server detected an infinite loop while processing the request..
        /// </summary>
        internal static string LoopDetected {
            get {
                return ResourceManager.GetString("LoopDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming method is not applicable for this resource..
        /// </summary>
        internal static string MethodNotAllowed {
            get {
                return ResourceManager.GetString("MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is unable to produce a response..
        /// </summary>
        internal static string MisdirectedRequest {
            get {
                return ResourceManager.GetString("MisdirectedRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client needs to authenticate to gain network access..
        /// </summary>
        internal static string NetworkAuthenticationRequired {
            get {
                return ResourceManager.GetString("NetworkAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming request indicates this resource is not in an acceptable format..
        /// </summary>
        internal static string NotAcceptable {
            get {
                return ResourceManager.GetString("NotAcceptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Further extensions to the requests are needed to be processed..
        /// </summary>
        internal static string NotExtended {
            get {
                return ResourceManager.GetString("NotExtended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The target resource was not found..
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request method has not been implemented by the server..
        /// </summary>
        internal static string NotImplemented {
            get {
                return ResourceManager.GetString("NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is required to access this resource..
        /// </summary>
        internal static string PaymentRequired {
            get {
                return ResourceManager.GetString("PaymentRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server doesn&apos;t meet the request&apos;s preconditions..
        /// </summary>
        internal static string PreconditionFailed {
            get {
                return ResourceManager.GetString("PreconditionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server requires the request to be conditional..
        /// </summary>
        internal static string PreconditionRequired {
            get {
                return ResourceManager.GetString("PreconditionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy authentication is required to access this resource..
        /// </summary>
        internal static string ProxyAuthenticationRequired {
            get {
                return ResourceManager.GetString("ProxyAuthenticationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request resource range can&apos;t be satisfiable..
        /// </summary>
        internal static string RequestedRangeNotSatisfiable {
            get {
                return ResourceManager.GetString("RequestedRangeNotSatisfiable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request&apos;s payload was too large..
        /// </summary>
        internal static string RequestEntityTooLarge {
            get {
                return ResourceManager.GetString("RequestEntityTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request sent headers that are too large..
        /// </summary>
        internal static string RequestHeaderFieldsTooLarge {
            get {
                return ResourceManager.GetString("RequestHeaderFieldsTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server timed out waiting for the request..
        /// </summary>
        internal static string RequestTimeout {
            get {
                return ResourceManager.GetString("RequestTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request&apos;s URL was too large..
        /// </summary>
        internal static string RequestUriTooLong {
            get {
                return ResourceManager.GetString("RequestUriTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server is temporarily unavailable, likely due to maintenance..
        /// </summary>
        internal static string ServiceUnavailable {
            get {
                return ResourceManager.GetString("ServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client has sent too many requests to the server..
        /// </summary>
        internal static string TooManyRequests {
            get {
                return ResourceManager.GetString("TooManyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization is required to access this resource..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested resource has been taken down in response to a legal demand..
        /// </summary>
        internal static string UnavailableForLegalReasons {
            get {
                return ResourceManager.GetString("UnavailableForLegalReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was unable to be followed due to semantic errors..
        /// </summary>
        internal static string UnprocessableEntity {
            get {
                return ResourceManager.GetString("UnprocessableEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request&apos;s entity was of an unsupported media type..
        /// </summary>
        internal static string UnsupportedMediaType {
            get {
                return ResourceManager.GetString("UnsupportedMediaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request must upgrade to a different protocol to be satisfied..
        /// </summary>
        internal static string UpgradeRequired {
            get {
                return ResourceManager.GetString("UpgradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular reference occurred during content negotiation..
        /// </summary>
        internal static string VariantAlsoNegotiates {
            get {
                return ResourceManager.GetString("VariantAlsoNegotiates", resourceCulture);
            }
        }
    }
}
